#ifndef _GAME_FLAG_H
#define _GAME_FLAG_H

#include "dolphin.h"

#define FLAGNUM(group, index) ((group)|(index))

typedef enum {
    FLAG_GROUP_SAVE = (0 << 16),
    FLAG_GROUP_COMMON = (1 << 16),
    FLAG_GROUP_BOARD = (2 << 16),
    FLAG_GROUP_SYSTEM = (3 << 16)
} FLAG_GROUP;

typedef enum {
    FLAG_STORY_MAP1_COMPLETE = FLAGNUM(FLAG_GROUP_SAVE, 2),
    FLAG_STORY_MAP2_COMPLETE = FLAGNUM(FLAG_GROUP_SAVE, 3),
    FLAG_STORY_MAP3_COMPLETE = FLAGNUM(FLAG_GROUP_SAVE, 4),
    FLAG_STORY_MAP4_COMPLETE = FLAGNUM(FLAG_GROUP_SAVE, 5),
    FLAG_STORY_MAP5_COMPLETE = FLAGNUM(FLAG_GROUP_SAVE, 6),
    FLAG_STORY_MAP6_COMPLETE = FLAGNUM(FLAG_GROUP_SAVE, 7),
    FLAG_BOARD_LAST5 = FLAGNUM(FLAG_GROUP_SAVE, 8),
    FLAG_MGINST_ON = FLAGNUM(FLAG_GROUP_SAVE, 11),
    
    FLAG_BOARD_SAVEINIT = FLAGNUM(FLAG_GROUP_COMMON, 0),
    FLAG_BOARD_OPENING = FLAGNUM(FLAG_GROUP_COMMON, 1),
    FLAG_BOARD_MG = FLAGNUM(FLAG_GROUP_COMMON, 2),
    FLAG_BOARD_MG_KOOPA = FLAGNUM(FLAG_GROUP_COMMON, 3),
    FLAG_BOARD_MG_VS = FLAGNUM(FLAG_GROUP_COMMON, 4),
    FLAG_BOARD_MG_KETTOU = FLAGNUM(FLAG_GROUP_COMMON, 5),
    FLAG_BOARD_MG_DONKEY = FLAGNUM(FLAG_GROUP_COMMON, 6),
    FLAG_MG_PAUSE_OFF = FLAGNUM(FLAG_GROUP_COMMON, 11),
    FLAG_BOARD_TUTORIAL = FLAGNUM(FLAG_GROUP_COMMON, 14),
    FLAG_MG_PRACTICE = FLAGNUM(FLAG_GROUP_COMMON, 15),
    FLAG_MG_CIRCUIT = FLAGNUM(FLAG_GROUP_COMMON, 16),
    FLAG_BOARD_MOVE_DONE = FLAGNUM(FLAG_GROUP_COMMON, 18),
    FLAG_BOARD_INIT = FLAGNUM(FLAG_GROUP_COMMON, 20),
    FLAG_BOARD_PAUSE = FLAGNUM(FLAG_GROUP_COMMON, 22),
    FLAG_BOARD_CAMERA_MOT = FLAGNUM(FLAG_GROUP_COMMON, 25),
    FLAG_BOARD_STAR_MUS_RESET = FLAGNUM(FLAG_GROUP_COMMON, 27),
    FLAG_BOARD_STORY_END = FLAGNUM(FLAG_GROUP_COMMON, 28),
    FLAG_BOARD_PAUSE_DISABLE = FLAGNUM(FLAG_GROUP_COMMON, 30),
    FLAG_BOARD_EXIT = FLAGNUM(FLAG_GROUP_COMMON, 32),
    FLAG_BOARD_TURN_NOSTART = FLAGNUM(FLAG_GROUP_COMMON, 33),
    FLAG_BOARD_STAR_RESET = FLAGNUM(FLAG_GROUP_COMMON, 34),
    
    FLAG_BOARD_NOMG = FLAGNUM(FLAG_GROUP_BOARD, 0),
    FLAG_BOARD_DEBUG = FLAGNUM(FLAG_GROUP_BOARD, 1),
    FLAG_BOARD_DICE_SHORT = FLAGNUM(FLAG_GROUP_BOARD, 4),
    
    FLAG_INST_MG_MODE = FLAGNUM(FLAG_GROUP_SYSTEM, 1),
    FLAG_INST_DECA = FLAGNUM(FLAG_GROUP_SYSTEM, 2),
    FLAG_INST_NO_HISCHG = FLAGNUM(FLAG_GROUP_SYSTEM, 3),
    FLAG_SYSTEM_5 = FLAGNUM(FLAG_GROUP_SYSTEM, 5),
} FLAG;

BOOL _CheckFlag(u32 flag);
void _SetFlag(u32 flag);
void _ClearFlag(u32 flag);
void _InitFlag(void);

#define CheckFlag _CheckFlag
#define SetFlag _SetFlag
#define ClearFlag _ClearFlag
#define InitFlag _InitFlag

#endif