#ifndef _GAME_GAMEWORK_ENUM_H
#define _GAME_GAMEWORK_ENUM_H

#define GW_DECA_SCORE_MAX 10
#define GW_RENSHO_MG_MAX 100
#define GW_BOARD_WORK_SIZE 32

#define GW_PLAYER_GRAPH_SIZE 52

#define GW_MGNO_BASE 601
#define GW_MGNO_NONE 0xFFFF

#define GW_SINGLE_MGWIN_MAX 99

#define GW_PLAYER_COIN_MAX 999
#define GW_PLAYER_STAR_MAX 999

#define GW_BANK_STAR_MAX 9999

#define GW_MG_PLAY_NUM_MAX 10000

#include "game/window_enum.h"

typedef enum {
    GW_MG_TIME_DAY, //0
    GW_MG_TIME_NIGHT //1
} GW_MG_TIME;

typedef enum {
    GW_BANK_FLAG_MAX = 63
} GW_BANK_FLAG;

typedef enum {
    GW_MIRACLE_BOOK_FLAG_MAX = 63
} GW_MIRACLE_BOOK_FLAG;

typedef enum {
    GW_SINGLE_PRIZE_FLAG_MAX = 63
} GW_SINGLE_PRIZE_FLAG;

typedef enum {
    GW_PLAYER_COM_DIF_EASY, //0
    GW_PLAYER_COM_DIF_NORMAL, //1
    GW_PLAYER_COM_DIF_HARD, //2
    GW_PLAYER_COM_DIF_VERYHARD, // 3
    GW_PLAYER_COM_DIF_MAX, //4
} GW_PLAYER_COM_DIF;

typedef enum {
    GW_RECORD_NONE = -1,
    GW_RECORD_M606 = 0, //0
    GW_RECORD_M608, //1
    GW_RECORD_M618, //2
    GW_RECORD_M638, //3
    GW_RECORD_M648, //4
    GW_RECORD_M650, //5
    GW_RECORD_M652, //6
    GW_RECORD_M678, //7
    GW_RECORD_MAX //8
} GW_RECORD_NO;

typedef enum {
    GW_BOARD_NULL = -1,
    GW_BOARD_W01 = 0,
    GW_BOARD_W02, //1
    GW_BOARD_W03, //2
    GW_BOARD_W04, //3
    GW_BOARD_W05, //4
    GW_BOARD_W06, //5
    GW_BOARD_S01, //6
    GW_BOARD_S02, //7
    GW_BOARD_S03, //8
    GW_BOARD_W10, //9
    GW_BOARD_W11, //10
    GW_BOARD_MAX //11
} GW_BOARD_NO;

typedef enum {
    GW_CHARA_NULL = -1,
    GW_CHARA_MARIO = 0,
    GW_CHARA_LUIGI, //1
    GW_CHARA_PEACH, //2
    GW_CHARA_YOSHI, //3
    GW_CHARA_WARIO, //4
    GW_CHARA_DAISY, //5
    GW_CHARA_WALUIGI, //6
    GW_CHARA_KINOPIO, //7
    GW_CHARA_TERESA, //8
    GW_CHARA_MINIKOOPA, //9
    GW_CHARA_KINOPIKO, //10
    GW_CHARA_MINIKOOPAR, //11
    GW_CHARA_MINIKOOPAG, //12
    GW_CHARA_MINIKOOPAB, //13
    GW_CHARA_MAX //14
} GW_CHARA_ID;

typedef enum {
    GW_PLAYER_1, //0
    GW_PLAYER_2, //1
    GW_PLAYER_3, //2
    GW_PLAYER_4, //3
    GW_PLAYER_MAX
} GW_PLAYER_ID;

typedef enum {
    GW_PLAYER_TYPE_MAN, //0
    GW_PLAYER_TYPE_COM, //1
    GW_PLAYER_TYPE_MAX
} GW_PLAYER_TYPE;

typedef enum {
    GW_MESS_SPEED_FAST, //0
    GW_MESS_SPEED_NORMAL, //1
    GW_MESS_SPEED_SLOW, //2
    GW_MESS_SPEED_MAX //3
} GW_MESS_SPEED;

typedef enum {
    GW_SAVE_MODE_ALWAYS, //0
    GW_SAVE_MODE_NEVER, //1
    GW_SAVE_MODE_TURN, //2
    GW_SAVE_MODE_MAX //3
} GW_SAVE_MODE;

typedef enum {
    GW_MINIGAME_PACK_ALL, //0
    GW_MINIGAME_PACK_EASY, //1
    GW_MINIGAME_PACK_ACTION, //2
    GW_MINIGAME_PACK_HARD, //3
    GW_MINIGAME_PACK_WEIRD, //4
    GW_MINIGAME_PACK_MAX, //5
} GW_MINIGAME_PACK;

#endif