#ifndef MESSNUM_MG_INST_H
#define MESSNUM_MG_INST_H

#include "messdir_enum.h"

enum {
    MG_INST_SYS_HELP_START = MESSNUM(MESS_MG_INST_SYS, 0),
    MG_INST_SYS_HELP_PRACTICE, //1
    MG_INST_SYS_INST, //2
    MG_INST_SYS_CONTROL1, //3
    MG_INST_SYS_CONTROL2, //4
    MG_INST_SYS_HELP1, //5
    MG_INST_SYS_HELP2, //6
    MG_INST_SYS_CONTROL, //7
    MG_INST_SYS_HELP, //8
    MG_INST_SYS_EXIT, //9
    MG_INST_SYS_START, //10
    MG_INST_SYS_FINISH, //11
    MG_INST_SYS_WIN, //12
    MG_INST_SYS_TIE, //13
    MG_INST_SYS_RECORD_NEW, //14
    MG_INST_SYS_CHAR_MINIKOOPA, //15
    MG_INST_SYS_PAUSE, //16
    
};



#endif