#ifndef DATANUM_GAMEMES_H
#define DATANUM_GAMEMES_H

#include "datadir_enum.h"

enum {
    GAMEMES_ANM_timer = DATANUM(DATA_gamemes, 0),
    GAMEMES_ANM_timer_back, //1
    GAMEMES_ANM_timer_new, //2
    GAMEMES_ANM_digit, //3
    GAMEMES_ANM_score_red, //4
    GAMEMES_ANM_score_blue, //5
    GAMEMES_ANM_practice, //6
    GAMEMES_ANM_record_num, //7
    GAMEMES_ANM_record_crown, //8
    GAMEMES_ANM_record_new, //9
    GAMEMES_ANM_record_new_us, //10
    GAMEMES_ANM_record_new_ge, //11
    GAMEMES_ANM_record_new_fr, //12
    GAMEMES_ANM_record_new_it, //13
    GAMEMES_ANM_record_new_sp, //14
    GAMEMES_ANM_record_dot, //15
    GAMEMES_ANM_record_yard, //16
    GAMEMES_ANM_record_foot, //17
    GAMEMES_ANM_num_0, //18
    GAMEMES_ANM_num_1, //19
    GAMEMES_ANM_num_2, //20
    GAMEMES_ANM_num_3, //21
    GAMEMES_ANM_num_4, //22
    GAMEMES_ANM_num_5, //23
    GAMEMES_ANM_num_6, //24
    GAMEMES_ANM_num_7, //25
    GAMEMES_ANM_num_8, //26
    GAMEMES_ANM_num_9, //27
    GAMEMES_ANM_upper_a, //28
    GAMEMES_ANM_upper_b, //29
    GAMEMES_ANM_upper_c, //30
    GAMEMES_ANM_upper_d, //31
    GAMEMES_ANM_upper_e, //32
    GAMEMES_ANM_upper_f, //33
    GAMEMES_ANM_upper_g, //34
    GAMEMES_ANM_upper_h, //35
    GAMEMES_ANM_upper_i, //36
    GAMEMES_ANM_upper_j, //37
    GAMEMES_ANM_upper_k, //38
    GAMEMES_ANM_upper_l, //39
    GAMEMES_ANM_upper_m, //40
    GAMEMES_ANM_upper_n, //41
    GAMEMES_ANM_upper_o, //42
    GAMEMES_ANM_upper_p, //43
    GAMEMES_ANM_upper_q, //44
    GAMEMES_ANM_upper_r, //45
    GAMEMES_ANM_upper_s, //46
    GAMEMES_ANM_upper_t, //47
    GAMEMES_ANM_upper_u, //48
    GAMEMES_ANM_upper_v, //49
    GAMEMES_ANM_upper_w, //50
    GAMEMES_ANM_upper_x, //51
    GAMEMES_ANM_upper_y, //52
    GAMEMES_ANM_upper_z, //53
    GAMEMES_ANM_lower_a, //54
    GAMEMES_ANM_lower_b, //55
    GAMEMES_ANM_lower_c, //56
    GAMEMES_ANM_lower_d, //57
    GAMEMES_ANM_lower_e, //58
    GAMEMES_ANM_lower_f, //59
    GAMEMES_ANM_lower_g, //60
    GAMEMES_ANM_lower_h, //61
    GAMEMES_ANM_lower_i, //62
    GAMEMES_ANM_lower_j, //63
    GAMEMES_ANM_lower_k, //64
    GAMEMES_ANM_lower_l, //65
    GAMEMES_ANM_lower_m, //66
    GAMEMES_ANM_lower_n, //67
    GAMEMES_ANM_lower_o, //68
    GAMEMES_ANM_lower_p, //69
    GAMEMES_ANM_lower_q, //70
    GAMEMES_ANM_lower_r, //71
    GAMEMES_ANM_lower_s, //72
    GAMEMES_ANM_lower_t, //73
    GAMEMES_ANM_lower_u, //74
    GAMEMES_ANM_lower_v, //75
    GAMEMES_ANM_lower_w, //76
    GAMEMES_ANM_lower_x, //77
    GAMEMES_ANM_lower_y, //78
    GAMEMES_ANM_lower_z, //79
    GAMEMES_ANM_dash, //80
    GAMEMES_ANM_apos, //81
    GAMEMES_ANM_upper_umlaut_a, //82
    GAMEMES_ANM_upper_umlaut_o, //83
    GAMEMES_ANM_upper_umlaut_u, //84
    GAMEMES_ANM_upper_eszett, //85
    GAMEMES_ANM_upper_grave_a, //86
    GAMEMES_ANM_upper_acute_a, //87
    GAMEMES_ANM_upper_grave_e, //88
    GAMEMES_ANM_upper_acute_e, //89
    GAMEMES_ANM_upper_grave_i, //90
    GAMEMES_ANM_upper_acute_i, //91
    GAMEMES_ANM_upper_grave_o, //92
    GAMEMES_ANM_upper_acute_o, //93
    GAMEMES_ANM_upper_grave_u, //94
    GAMEMES_ANM_upper_acute_u, //95
    GAMEMES_ANM_upper_tilde_n, //96
    GAMEMES_ANM_lower_grave_a, //97
    GAMEMES_ANM_lower_circumflex_a, //98
    GAMEMES_ANM_lower_umlaut_a, //99
    GAMEMES_ANM_lower_cedilla_c, //100
    GAMEMES_ANM_lower_grave_e, //101
    GAMEMES_ANM_lower_acute_e, //102
    GAMEMES_ANM_lower_circumflex_e, //103
    GAMEMES_ANM_lower_umlaut_e, //104
    GAMEMES_ANM_lower_circumflex_i, //105
    GAMEMES_ANM_lower_umlaut_i, //106
    GAMEMES_ANM_lower_circumflex_o, //107
    GAMEMES_ANM_lower_umlaut_o, //108
    GAMEMES_ANM_lower_grave_u, //109
    GAMEMES_ANM_lower_circumflex_u, //110
    GAMEMES_ANM_lower_umlaut_u, //111
    GAMEMES_ANM_lower_acute_a, //112
    GAMEMES_ANM_lower_grave_i, //113
    GAMEMES_ANM_lower_acute_i, //114
    GAMEMES_ANM_lower_grave_o, //115
    GAMEMES_ANM_lower_acute_o, //116
    GAMEMES_ANM_lower_acute_u, //117
    GAMEMES_ANM_lower_tilde_n, //118
    GAMEMES_ANM_punct_flip_exclamation, //119
    GAMEMES_ANM_punct_minus, //120
    GAMEMES_ANM_punct_exclamation, //121
    GAMEMES_ANM_punct_hatena, //122
    GAMEMES_ANM_punct_period, //123
    GAMEMES_ANM_punct_empty1, //124
    GAMEMES_ANM_punct_empty2, //125
};

#endif